# Generated by Django 5.2.4 on 2025-07-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254)),
                ('contact', models.PositiveIntegerField()),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
