# Generated by Django 5.2.4 on 2025-07-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
